apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:JxpVvHy+XZr2kDLFotIiYin/iVO64+2dlCCF4b4VLRnES+or,iv:/WqFqSeaDfQTkMX6I5A2Sj1hM/gnTHNXiTMTxSOdxVw=,tag:DYm5lG/n7x6vXfQiyCXhHQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:am16yC99a5nUM7Hqd1Fk4y0ZDlfw6fwTJN+fNZEv/HHAniwgYOaWVc5xzUoeRcliyZ1kL6AULXt9ELeaxD+nfVrzmGFM8+bM6bAq3xzg/FNQrga85xyUTpybMMkwAs2vsrQYx7PKQUf3F+LjmAw6PkLzxAHBo19tLXmG8UE9uP/LsFAnEaWHXoA1HQaZHX5bEKoUokVOlSEDyWPhGfpQEe1c9mThLrtjPYqo9leI+g==,iv:U7fdc7mjNoMN8om+0EkJD+q5FOS89nQZp7rDqvoX6EA=,tag:aUbTrpvptwhmLlIaNv1kAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a388gvypkgc9qt39s59utm3ymsm39nkyvte335awkt26syen8drs78r6gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcHl5TWRIVnAramU2MnhT
            cmVkS2R0Uk9GUXZrWkhSam1Ud3hnY3U1MnkwCmFnMlgvcEJvYXoxOXRiWWlrZThq
            LzlKeS8zNjNjdFBScFdobkRJcHZ6aXMKLS0tIGdRSVNVZGNmZW8rU3VtMiswU0hJ
            NGtJcUppWVowamM2TXdsbnhUUFludkEKFN37swarkt6Ddeodzt0jC25dnmjNpmGM
            xcuWF/bBoRwe+WAOP+dGqRckdUP6Y+ESSRLu7xGYG1cufaTLdA/ibg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-27T12:35:49Z"
    mac: ENC[AES256_GCM,data:/5+9pcdtZPiC2W99/Rd0EXY4pwWwFLUVHzQdi/UcjPrb6Olkq0bUFELvnBxgFf+OsrXYhXRGADdAbsP1eBAnjcmRd9ar77bQomhucw2RSOaxtfM5kHpw3hq7RDbEzmiVw+/QmXm4VUMNKn+7Vs0oprqloikNf28mFPnrinL5daE=,iv:/Zr/+KGhwxJ7BoytmveHBqu6XL78cruJVX17ioUOt5w=,tag:K8olKnACPzWA5l6JpCloMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
