apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:1tpT6l/sYpno81V7KQMKtyjtma3PMFhnozL8ntWi+z4VwSseTpw5/Q==,iv:MIi/m5IVOSfINwmDOoUY0BdF52ijP1TTqj1nk4vSUGY=,tag:HVwhvO8aZr5lnocCqB1J8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a388gvypkgc9qt39s59utm3ymsm39nkyvte335awkt26syen8drs78r6gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTVRlSTg1K1M2a01jRmZq
            Y1F6MjM1dWFnVFVnZGZ5ay84RnZXRVo5NEg0CkVoNzNSZHFZVlUwRXlyMmx0UVp6
            cEQzK2JYb0hENEZzS3pqSWV1NFZTeE0KLS0tIFJmTG5YYmYvQitJcXpxdHU5N2FL
            Mk0vUDFucG5NS2RXdmdQckVHY01xbmcKLkcWT9cErSA78lxe2tNchTUp8P+nJJ0F
            r/oQl8Wmy8qjtV5rec3wfYWhCGlW2O1/O0A1h7xQJIHi2rp4Wr0Ikg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-27T12:35:49Z"
    mac: ENC[AES256_GCM,data:eMFLh5ORICgkZCsTTzySYPjNK8F6z89mBQibj8yYE4EmbC0QzOdWtb75j8K9FBYq9Z8uaAQycTO+FmuMDa8cPHTAUxj2UF+Q0fKmqT63WToJze2gtjVMjTMIx1O8lZW2y7Jorkqp0FOPL2BJIuY4+/wPYLFTvfJxy3Ty1M0TrHM=,iv:GATnKeOwRWmlSRJLJciPjNVXy6Sz+ZT7PLXO/HwyFN8=,tag:T69+aA7PS4594dfT3sp+5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
