apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:EmLrKyTaykYJRgvK9g==,iv:CNF4qrqDs9vRqOVCNWN66o2zWGISG353jgwrDIPH/ig=,tag:yKKQk73mCQA/ui/wewVXpA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:g3omRTmYj+2sTU3MfG1ih5V0yg==,iv:1LgpwokOzOp5d4DgJbe3FlfTXV8rgqZDl8E25LnKW5U=,tag:QvRV3+Y1+U3hPrrZOOKXCQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:UyizIUs6QPYBhe1d/ySVBsGXI347AZYdRn71vfLoztdSlriQ,iv:0aKgm4/IVZLUg2IMXN6yc/oMzBcmSH4Xk5E9xqWYmts=,tag:Km5j8BWtdqxbhmwWdsEyxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a388gvypkgc9qt39s59utm3ymsm39nkyvte335awkt26syen8drs78r6gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dnlCZk9HMzJEc1BuWFcr
            MGw4dWZtVFRaU05tbmYwMERvd3NpM2RLdTE4CnAvYU96blZNZVhKNWRNcXh4c21N
            TW5uS2ZiN2p3Z1RnMGdvQ3pzam5vd3MKLS0tIEFCeUwvL3R0Ym5iWVVTVXdVcmZF
            WmdoZlhGWUg1Ny9JMXZpUE9ObTViYlUKeN4hD3mvp7/TpUqs080EdRtbYz6MB2q5
            3gIAu37wYmWqJU5QiGklttUaClxfdruLIXbYI2wxHbftyBOFs243zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-27T13:17:47Z"
    mac: ENC[AES256_GCM,data:cSp590Gis/oCs9dhU+oOBV706mQqVvU/pe5h4KrEManiB1W5jQPA3PgluLSTFrZKOrv9MJNwl4c1NwNUrhtpLzZAq0gsXhKLf6qdWkzJiKESBbe8oNLLQxRpbKkMLGCYtQJ4KfN+D8mL6c0leXmp9UEzRGHeFV/8HKe1f+Rys38=,iv:OZhQi8RbfOixJT5f7ol5KzeJx9Z+Xi0fv+YrtsFqWEk=,tag:otE8LccFkyN1uEjX+Wp6yQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
