apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:HKoDwNjqeXVlHdcksLtwXfuIop2bP8yyeP8QjZXU5Ipi0UCx9hzUmQ==,iv:cU5KeKqSDnR21kUtHqfO45nAPbwUXdrbwTe38rlnN94=,tag:j8AQ4FRFcaF0H6oaHeAEhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a388gvypkgc9qt39s59utm3ymsm39nkyvte335awkt26syen8drs78r6gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTFladmdBcGovYlphT0Ex
            ejl3RjByYWNocFMrYmFXcE4vc1J6NE1YRXh3CkFxRis1TW4wcXIzd2tjcTRtRTBh
            cXQ2aHQxRHJaNmFYa0lNZzllS3oxVHMKLS0tIGJxeXNldWY1Q2IwTE95VmhGQ1FP
            dW0zVkJDcHR2SjYxTnFvTDZRWDZZcFkKAAs4kol6WvZfQpXNKWJnaveM3nmKqa0n
            nAa/4cZKCTl8J0YRzUse1KeZ6Fu3OBb7QBBQgHXX9Xvjf26Y1HETGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-27T11:42:59Z"
    mac: ENC[AES256_GCM,data:7mLEIQ0XvV+bIf8XUWI4xTx6+wQCcJSjLWAs/7z2PLoo3SOd5cLkNUZjGHNukxYZAV+ew67WHaD7VkkF90CKyBdxwgtGTjbSBr8IPTV6VpboSTz9htTiNam2dnrxhRSynC0KbF+ACH5RhDeu8PKoSUddz+qkVKZFqRu4iIqAl9k=,iv:er7qlCjE4epIUqc5eyLRTKUkPNQMsUy3oT7gOC2R8rQ=,tag:I6Nn8uiliTvda32tmneqjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
